# Generated by getCourseLinks.py.
course_links = {
    "2026 Trimester 3": {
        "2026 September Term - 01.011  Professional Practice Programme": "https://edimension.sutd.edu.sg/ultra/courses/_6210_1/outline",
        "2026 September Term - 01.010  Freshmore Communication Programme-Belinda": "https://edimension.sutd.edu.sg/ultra/courses/_6489_1/outline",
        "2026 September Term - 02.003  Social Science Understanding Behaviour, Culture & Society_Jin": "https://edimension.sutd.edu.sg/ultra/courses/_6335_1/cl/outline",
        "2026 September Term - 02.003  Social Science Understanding Behaviour, Culture & Society": "https://edimension.sutd.edu.sg/ultra/courses/_6249_1/cl/outline",
        "2026 September Term - 01.010  Freshmore Communication Programme": "https://edimension.sutd.edu.sg/ultra/courses/_6322_1/outline",
        "2026 September Term - 10.013  Calculus": "https://edimension.sutd.edu.sg/ultra/courses/_6272_1/cl/outline",
        "2026 September Term - 10.016  Sustainability Science and System Thinking": "https://edimension.sutd.edu.sg/ultra/courses/_6274_1/cl/outline"
    },
    "2026 Trimester 2": {
        "ILP 2026 Chemistry": "https://edimension.sutd.edu.sg/ultra/courses/_6199_1/cl/outline"
    },
    "2025 Trimester 3": {
        "2025 September Term - 01.010  Freshmore Communication Programme-Rashmi": "https://edimension.sutd.edu.sg/ultra/courses/_5684_1/cl/outline",
        "2025 September Term - 01.010  Freshmore Communication Programme-Belinda": "https://edimension.sutd.edu.sg/ultra/courses/_5865_1/cl/outline",
        "2025  English Writing Entrance Test (EWET)": "https://edimension.sutd.edu.sg/ultra/courses/_5678_1/cl/outline",
        "2025 September Term - 01.010  Freshmore Communication Programme": "https://edimension.sutd.edu.sg/ultra/courses/_5683_1/cl/outline",
        "2025 September Term - 01.011  Professional Practice Programme": "https://edimension.sutd.edu.sg/ultra/courses/_5741_1/cl/outline",
        "2025 September Term - 03.007A  Innovating with Design and AI-1 (IDeA-1)": "https://edimension.sutd.edu.sg/ultra/courses/_5797_1/cl/outline",
        "2025 September Term - 10.013  Modelling and Analysis": "https://edimension.sutd.edu.sg/ultra/courses/_5756_1/cl/outline",
        "2025 September Term - 02.003  Social Science Understanding Behaviour, Culture & Society": "https://edimension.sutd.edu.sg/ultra/courses/_5725_1/cl/outline",
        "2025 September Term - 01.018  Design Thinking Project I": "https://edimension.sutd.edu.sg/ultra/courses/_5751_1/cl/outline",
        "2025 September Term - 10.015  Physical World": "https://edimension.sutd.edu.sg/ultra/courses/_5689_1/cl/outline",
        "2025 September Term - 01.012  UPOP Essential Module": "https://edimension.sutd.edu.sg/ultra/courses/_5745_1/cl/outline",
        "2025 September Term - 10.025  Computational Thinking For Design": "https://edimension.sutd.edu.sg/ultra/courses/_5796_1/cl/outline"
    }
}
