# Generated by getCourseLinks.py, here for reference. Do not edit manually.
course_links = {
    "2026 Trimester 3": {
        "2026 September Term - 01.011  Professional Practice Programme": "https://edimension.sutd.edu.sg/ultra/courses/_6210_1/outline",
        "2026 September Term - 01.010  Freshmore Communication Programme-Belinda": "https://edimension.sutd.edu.sg/ultra/courses/_6489_1/outline",
        "2026 September Term - 02.003  Social Science Understanding Behaviour, Culture & Society_Jin": "https://edimension.sutd.edu.sg/ultra/courses/_6335_1/cl/outline",
        "2026 September Term - 02.003  Social Science Understanding Behaviour, Culture & Society": "https://edimension.sutd.edu.sg/ultra/courses/_6249_1/cl/outline",
        "2026 September Term - 01.010  Freshmore Communication Programme": "https://edimension.sutd.edu.sg/ultra/courses/_6322_1/outline",
        "2026 September Term - 10.013  Calculus": "https://edimension.sutd.edu.sg/ultra/courses/_6272_1/cl/outline",
        "2026 September Term - 10.016  Sustainabiity Science and System Thinking" : "https://edimension.sutd.edu.sg/webapps/blackboard/execute/modulepage/view?course_id=_6274_1",
#     "ILP 2026: Chemistry ": "https://edimension.sutd.edu.sg/webapps/blackboard/execute/modulepage/view?course_id=_6119_1"
#     ...
# }