import json
import re
import sys
from pathlib import Path

import requests

try:
    from headers import cookies, headers
except (ImportError, AttributeError):
    cookies = {}
    headers = {}


API_BASE_URL = "https://edimension.sutd.edu.sg/learn/api/v1"
OUTPUT_FILE = Path(__file__).with_name("course_links.py")


def validate_credentials():
    if not headers or not cookies:
        raise RuntimeError(
            "headers.py is empty. Follow the steps in the README to update your headers.py " \
            "with fresh cookies and request headers from eDimension." \
        )


def safe_name(value):
    value = re.sub(r'[/\\:*?"<>|]', "", " ".join(value.split()))
    return value.rstrip(". ") or "Unnamed"


def request_headers():
    return {
        **headers,
        "Accept": "application/json",
        "Referer": "https://edimension.sutd.edu.sg/",
    }


def fetch_user_id(session):
    response = session.get(
        f"{API_BASE_URL}/users/me",
        headers=request_headers(),
        cookies=cookies,
        timeout=30,
    )
    if response.status_code in (401, 403):
        raise RuntimeError(
            f"Blackboard rejected the request ({response.status_code}). "
            "Cookies are outdated; follow the steps in the README to update "
            "headers.py with fresh cookies and request headers from eDimension."
        )
    response.raise_for_status()
    user_id = response.json().get("id")
    if not user_id:
        raise RuntimeError("Blackboard did not return a user ID from /users/me.")
    return user_id


def fetch_courses():
    validate_credentials()
    with requests.Session() as session:
        user_id = fetch_user_id(session)
        api_url = (
            f"{API_BASE_URL}/users/{user_id}/memberships"
        "?expand=course.effectiveAvailability,course.permissions,courseRole"
        "&includeCount=true&limit=10000"
        )
        response = session.get(
            api_url,
            headers=request_headers(),
            cookies=cookies,
            timeout=30,
        )
        if response.status_code in (401, 403):
            raise RuntimeError(
                f"Blackboard rejected the request ({response.status_code}). "
                "Cookies are outdated; follow the steps in the README to update "
                "headers.py with fresh cookies and request headers from eDimension."
            )
        response.raise_for_status()
        payload = response.json()

    courses = {}
    for membership in payload.get("results", []):
        course = membership.get("course") or {}
        term = ((course.get("term") or {}).get("description") or {}).get("rawText")
        display_name = course.get("displayName")
        link = course.get("externalAccessUrl")

        if not term or not display_name or not link:
            continue

        term = safe_name(term)
        display_name = safe_name(display_name)
        courses.setdefault(term, {})[display_name] = link

    return courses


def write_course_links(courses):
    contents = "# Generated by getCourseLinks.py.\ncourse_links = "
    contents += json.dumps(courses, indent=4, ensure_ascii=True)
    contents += "\n"
    OUTPUT_FILE.write_text(contents, encoding="utf-8")


if __name__ == "__main__":
    try:
        course_links = fetch_courses()
        write_course_links(course_links)
        course_count = sum(len(courses) for courses in course_links.values())
        print(f"Wrote {course_count} courses to {OUTPUT_FILE}")
    except (requests.RequestException, RuntimeError, ValueError) as error:
        print(f"Error fetching Blackboard courses: {error}", file=sys.stderr)
        sys.exit(1)